ccc_dataSources = {
    "citations":{
       "selected":true,
       "filepath":"data/science.csv",
       "groups":null
    },
    "papers":{
       "selected":false,
       "filepath":"data/science.csv",
       "groups":null
    },
    "roads":{
       "selected":false,
       "filepath":"data/roads.csv",
       "groups":{
          "chinaOnly":false,
          "usOnly":false,
          "highways":false,
          "expressways":false
       }
    },
    "internet":{
       "selected":false,
       "filepath":"data/internet.csv",
       "groups":{
          "chinaOnly":false,
          "usOnly":false,
          "broadband":false,
          "access":false,
          "mobile":false
       }
    },
    "patent":{
       "selected":false,
       "filepath":"data/patent.csv",
       "groups":null
    }
 }

